#ifndef TEST_OPENMPTARGET_BATCHED_DENSE_SERIAL_OTHER_CPP
#define TEST_OPENMPTARGET_BATCHED_DENSE_SERIAL_OTHER_CPP

#include <Test_OpenMPTarget.hpp>
#include <Test_Batched_Dense_Serial_Other.hpp>

#endif  // TEST_OPENMPTARGET_BATCHED_DENSE_SERIAL_OTHER_CPP
