#ifndef TEST_OPENMPTARGET_BATCHED_DENSE_SERIALSVD_CPP
#define TEST_OPENMPTARGET_BATCHED_DENSE_SERIALSVD_CPP

#include <Test_OpenMPTarget.hpp>
#include <Test_Batched_SerialSVD.hpp>

#endif  // TEST_OPENMPTARGET_BATCHED_DENSE_SERIALSVD_CPP
