version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    group:
      codeql-action:
        patterns:
          - "github/codeql-action/*"

  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: weekly
