#ifndef TEST_CUDA_BATCHED_DENSE_TEAM_TEAMVECTOR_VECTOR_CPP
#define TEST_CUDA_BATCHED_DENSE_TEAM_TEAMVECTOR_VECTOR_CPP

#include <Test_Cuda.hpp>
#include <Test_Batched_Dense_Team_TeamVector_Vector.hpp>

#endif  // TEST_CUDA_BATCHED_DENSE_TEAM_TEAMVECTOR_VECTOR_CPP
