#ifndef TEST_SERIAL_BATCHED_DENSE_SERIAL_BATCHEDGEMM_CPP
#define TEST_SERIAL_BATCHED_DENSE_SERIAL_BATCHEDGEMM_CPP

#include <Test_Serial.hpp>
#include <Test_Batched_Dense_Serial_BatchedGemm.hpp>

#endif  // TEST_SERIAL_BATCHED_DENSE_SERIAL_BATCHEDGEMM_CPP
