#ifndef TEST_THREADS_BATCHED_DENSE_SERIALSVD_CPP
#define TEST_THREADS_BATCHED_DENSE_SERIALSVD_CPP

#include <Test_Threads.hpp>
#include <Test_Batched_SerialSVD.hpp>

#endif  // TEST_THREADS_BATCHED_DENSE_SERIALSVD_CPP
