#ifndef TEST_THREADS_BATCHED_DENSE_SERIALEIGENDECOMPOSITION_CPP
#define TEST_THREADS_BATCHED_DENSE_SERIALEIGENDECOMPOSITION_CPP

#include <Test_Threads.hpp>
#include <Test_Batched_SerialEigendecomposition.hpp>
#include <Test_Batched_SerialEigendecomposition_Real.hpp>

#endif  // TEST_THREADS_BATCHED_DENSE_SERIALEIGENDECOMPOSITION_CPP
