#ifndef TEST_THREADS_BATCHED_DENSE_SERIAL_BATCHEDGEMM_CPP
#define TEST_THREADS_BATCHED_DENSE_SERIAL_BATCHEDGEMM_CPP

#include <Test_Threads.hpp>
#include <Test_Batched_Dense_Serial_BatchedGemm.hpp>

#endif  // TEST_THREADS_BATCHED_DENSE_SERIAL_BATCHEDGEMM_CPP
