include:
  - project: 'anl/ci-resources/defaults'
    ref: main
    file:
      - '/runners.yml'

Polaris:
  extends: .polaris-batch-runner
  variables:
    ANL_POLARIS_SCHEDULER_PARAMETERS: "-q debug -A kokkos_math -l select=1,walltime=60:00,filesystems=home"
  script:
    - module use /soft/modulefiles
    - module load PrgEnv-gnu
    - module load spack-pe-base
    - module load cmake
    - module load cudatoolkit-standalone/12.8.1
    - module load gcc
    - module list
    - export CMAKE_BUILD_PARALLEL_LEVEL=48
    - export HTTP_PROXY="http://proxy.alcf.anl.gov:3128"
    - export HTTPS_PROXY="http://proxy.alcf.anl.gov:3128"
    - export http_proxy="http://proxy.alcf.anl.gov:3128"
    - export https_proxy="http://proxy.alcf.anl.gov:3128"
    - export ftp_proxy="http://proxy.alcf.anl.gov:3128"
    - export no_proxy="admin,polaris-adminvm-01,localhost,*.cm.polaris.alcf.anl.gov,polaris-*,*.polaris.alcf.anl.gov,*.alcf.anl.gov"
    - git clone https://github.com/kokkos/kokkos.git
    - cmake -S kokkos
            -B kokkos_build
            -DCMAKE_INSTALL_PREFIX=kokkos_install
            -DBUILD_SHARED_LIBS=ON
            -DCMAKE_CXX_STANDARD=20
            -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_CXX_EXTENSIONS=OFF
            -DCMAKE_VERBOSE_MAKEFILE=ON
            -DKokkos_ENABLE_CUDA=ON
            -DKokkos_ARCH_AMPERE80=ON
            -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF
    - cmake --build kokkos_build --parallel
    - cmake --install kokkos_build --prefix kokkos_install
    - ctest -V -S .gitlab/alcf-ctest.cmake --test-dir kokkos-kernels_build --output-junit result_a100.xml
    - git clone https://github.com/kokkos/kokkos-kernels-performance.git
    - find kokkos-kernels_build/benchmarks -name "*.json" -exec mv {} kokkos-kernels-performance/Polaris \;
    - cd kokkos-kernels-performance
    - git add Polaris/*
    - git commit -m "polaris perofmance run"
    - git status
    - git push https://"$kokkos_kernels_perf_pat"@github.com/kokkos/kokkos-kernels-performance.git

  artifacts:
    when: always
    paths:
      - result_a100.xml
    reports:
      junit: result_a100.xml

Aurora:
  extends: .aurora-batch-runner
  variables:
    ANL_AURORA_SCHEDULER_PARAMETERS: "-q debug -A kokkos_math -l select=1,walltime=60:00,filesystems=flare"
  script:
    - module load cmake oneapi
    - module list
    - export HTTP_PROXY="http://proxy.alcf.anl.gov:3128"
    - export HTTPS_PROXY="http://proxy.alcf.anl.gov:3128"
    - export http_proxy="http://proxy.alcf.anl.gov:3128"
    - export https_proxy="http://proxy.alcf.anl.gov:3128"
    - export ftp_proxy="http://proxy.alcf.anl.gov:3128"
    - export no_proxy="admin,polaris-adminvm-01,localhost,*.cm.polaris.alcf.anl.gov,polaris-*,*.polaris.alcf.anl.gov,*.alcf.anl.gov"
    - git clone https://github.com/kokkos/kokkos.git
    - cmake -S kokkos
            -B kokkos/build
            -DCMAKE_INSTALL_PREFIX=kokkos-install
            -DBUILD_SHARED_LIBS=ON
            -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_VERBOSE_MAKEFILE=ON
            -DCMAKE_CXX_COMPILER=icpx
            -DKokkos_ARCH_NATIVE=ON
            -DKokkos_ENABLE_SYCL=ON
            -DKokkos_ARCH_INTEL_PVC=ON
            -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF
    - cmake --build kokkos/build --parallel
    - cmake --install kokkos/build --prefix kokkos-install
    - export ZES_ENABLE_SYSMAN=1
    - ctest -V -S .gitlab/aurora-ctest.cmake --test-dir kokkos-kernels_build -D Nightly --output-junit result_pvc1550.xml
    - git clone https://github.com/kokkos/kokkos-kernels-performance.git
    - find kokkos-kernels_build/benchmarks -name "*.json" -exec mv {} kokkos-kernels-performance/Aurora \;
    - cd kokkos-kernels-performance
    - git add Aurora/*
    - git commit -m "aurora perofmance run"
    - git status
    - git push https://"$kokkos_kernels_perf_pat"@github.com/kokkos/kokkos-kernels-performance.git

  artifacts:
    when: always
    paths:
      - result_pvc1550.xml
    reports:
      junit: result_pvc1550.xml
