stages:
  - test

hipcc:
  stage: test
  tags: [frontier, shell]
  id_tokens:
    OLCF_ID_TOKEN:
      aud: https://code.olcf.ornl.gov
  variables:
    OLCF_SERVICE_ACCOUNT: ums018_auser
  script:
    - module load rocm/6.3.1
    - export CRAYPE_LINK_TYPE=dynamic
    - export CMAKE_BUILD_PARALLEL_LEVEL=48
    - git clone https://github.com/kokkos/kokkos.git
    - cd kokkos
    - cmake -B build_hip -DCMAKE_CXX_COMPILER=hipcc -DKokkos_ENABLE_HIP=ON -DCMAKE_INSTALL_PREFIX=${PWD}/install
    - cmake --build build_hip --target install
    - cd ../..
    - ctest -VV -S ${PWD}/kokkos-kernels/.gitlab/frontier-ctest.cmake
    - rm -rf kokkos-kernels-performance
    - git clone https://github.com/kokkos/kokkos-kernels-performance.git
    - find kokkos-kernels/build/benchmarks -name "*.json" -exec mv {} kokkos-kernels-performance/Frontier \;
    - cd kokkos-kernels-performance
    - git add Frontier/*
    - git commit -m "frontier performance run"
    - git status
    - git push https://"$kokkos_kernels_perf_pat"@github.com/kokkos/kokkos-kernels-performance.git
