#ifndef TEST_HIP_BATCHED_DENSE_TEAM_TEAMVECTOR_VECTOR_CPP
#define TEST_HIP_BATCHED_DENSE_TEAM_TEAMVECTOR_VECTOR_CPP

#include <Test_HIP.hpp>
#include <Test_Batched_Dense_Team_TeamVector_Vector.hpp>

#endif  // TEST_HIP_BATCHED_DENSE_TEAM_TEAMVECTOR_VECTOR_CPP
