#ifndef TEST_SYCL_BATCHED_DENSE_SERIALSVD_CPP
#define TEST_SYCL_BATCHED_DENSE_SERIALSVD_CPP

#include <Test_SYCL.hpp>
#include <Test_Batched_SerialSVD.hpp>

#endif  // TEST_SYCL_BATCHED_DENSE_SERIALSVD_CPP
