#ifndef TEST_SYCL_BATCHED_DENSE_TEAM_TEAMVECTOR_VECTOR_CPP
#define TEST_SYCL_BATCHED_DENSE_TEAM_TEAMVECTOR_VECTOR_CPP

#include <Test_SYCL.hpp>
#include <Test_Batched_Dense_Team_TeamVector_Vector.hpp>

#endif  // TEST_SYCL_BATCHED_DENSE_TEAM_TEAMVECTOR_VECTOR_CPP
