#ifndef TEST_BATCHED_DENSE_SERIAL_OTHER_HPP
#define TEST_BATCHED_DENSE_SERIAL_OTHER_HPP

// Serial kernels
#include "Test_Batched_SerialAxpy.hpp"
#include "Test_Batched_SerialAxpy_Real.hpp"
#include "Test_Batched_SerialAxpy_Complex.hpp"
#include "Test_Batched_SerialEigendecomposition.hpp"
#include "Test_Batched_SerialEigendecomposition_Real.hpp"
#include "Test_Batched_SerialGemm.hpp"
#include "Test_Batched_SerialGemm_Real.hpp"
#include "Test_Batched_SerialGemm_Complex.hpp"
#include "Test_Batched_SerialGemv.hpp"
#include "Test_Batched_SerialGemv_Real.hpp"
#include "Test_Batched_SerialGemv_Complex.hpp"
#include "Test_Batched_SerialInverseLU.hpp"
#include "Test_Batched_SerialInverseLU_Real.hpp"
#include "Test_Batched_SerialInverseLU_Complex.hpp"
#include "Test_Batched_SerialLU.hpp"
#include "Test_Batched_SerialLU_Real.hpp"
#include "Test_Batched_SerialLU_Complex.hpp"
#include "Test_Batched_SerialMatUtil.hpp"
#include "Test_Batched_SerialMatUtil_Real.hpp"
#include "Test_Batched_SerialMatUtil_Complex.hpp"
#include "Test_Batched_SerialSolveLU.hpp"
#include "Test_Batched_SerialSolveLU_Real.hpp"
#include "Test_Batched_SerialSolveLU_Complex.hpp"
#include "Test_Batched_SerialTrmm.hpp"
#include "Test_Batched_SerialTrmm_Real.hpp"
#include "Test_Batched_SerialTrmm_Complex.hpp"
#include "Test_Batched_SerialTrsm.hpp"
#include "Test_Batched_SerialTrsm_Real.hpp"
#include "Test_Batched_SerialTrsm_Complex.hpp"
#include "Test_Batched_SerialTrsv.hpp"
#include "Test_Batched_SerialTrsv_Real.hpp"
#include "Test_Batched_SerialTrsv_Complex.hpp"
#include "Test_Batched_SerialTrtri.hpp"
#include "Test_Batched_SerialTrtri_Real.hpp"
#include "Test_Batched_SerialTrtri_Complex.hpp"
#include "Test_Batched_SerialSVD.hpp"

#endif  // TEST_BATCHED_DENSE_SERIAL_OTHER_HPP
