IF (NOT MAGMA_ROOT)
  SET(MAGMA_ROOT $ENV{MAGMA_ROOT})
ENDIF()
KOKKOSKERNELS_FIND_IMPORTED(MAGMA INTERFACE
  LIBRARIES magma magma_sparse
  HEADERS magma.h
)
TARGET_COMPILE_DEFINITIONS(MAGMA INTERFACE MAGMA_FORTRAN_MANGLING=ADD_)
IF (F77_BLAS_MANGLE STREQUAL "(name,NAME) name ## _")
  TARGET_COMPILE_DEFINITIONS(MAGMA INTERFACE ADD_)
ELSEIF (F77_BLAS_MANGLE STREQUAL "(name,NAME) NAME")
  TARGET_COMPILE_DEFINITIONS(MAGMA INTERFACE UPCASE)
ELSEIF (F77_BLAS_MANGLE STREQUAL "(name,NAME) name")
  TARGET_COMPILE_DEFINITIONS(MAGMA INTERFACE NOCHANGE)
ELSE ()
  MESSAGE(FATAL_ERROR "F77_BLAS_MANGLE ${F77_BLAS_MANGLE} detected while MAGMA only accepts Fortran mangling that is one of single underscore (-DADD_), uppercase (-DUPCASE), and no change (-DNOCHANGE)")
ENDIF()
