set(BLA_VENDOR Apple)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DACCELERATE_NEW_LAPACK")
find_package(BLAS REQUIRED)
kokkoskernels_create_imported_tpl(ACCELERATE INTERFACE LINK_LIBRARIES ${ACCELERATE_LIBRARIES})