#ifndef TEST_OPENMP_BATCHED_DENSE_SERIAL_BATCHEDGEMM_CPP
#define TEST_OPENMP_BATCHED_DENSE_SERIAL_BATCHEDGEMM_CPP

#include <Test_OpenMP.hpp>
#include <Test_Batched_Dense_Serial_BatchedGemm.hpp>

#endif  // TEST_OPENMP_BATCHED_DENSE_SERIAL_BATCHEDGEMM_CPP
