#ifndef TEST_OPENMP_BATCHED_DENSE_SERIAL_OTHER_CPP
#define TEST_OPENMP_BATCHED_DENSE_SERIAL_OTHER_CPP

#include <Test_OpenMP.hpp>
#include <Test_Batched_Dense_Serial_Other.hpp>

#endif  // TEST_OPENMP_BATCHED_DENSE_SERIAL_OTHER_CPP
