#ifndef TEST_OPENMP_BATCHED_DENSE_SERIALEIGENDECOMPOSITION_CPP
#define TEST_OPENMP_BATCHED_DENSE_SERIALEIGENDECOMPOSITION_CPP

#include <Test_OpenMP.hpp>
#include <Test_Batched_SerialEigendecomposition.hpp>
#include <Test_Batched_SerialEigendecomposition_Real.hpp>

#endif  // TEST_OPENMP_BATCHED_DENSE_SERIALEIGENDECOMPOSITION_CPP
