TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES KokkosCore KokkosContainers KokkosAlgorithms 
  LIB_OPTIONAL_TPLS quadmath MKL BLAS LAPACK CUBLAS CUSPARSE MAGMA SUPERLU CHOLMOD LAPACKE CBLAS ARMPL ROCBLAS ROCSPARSE
  TEST_OPTIONAL_TPLS yaml-cpp
)
