# Parameters related to building rocprim
ARG base_image

FROM ${base_image}
LABEL maintainer="saad.rahim@amd.com"

# Copy the deb package of rocprim into the container from host
COPY *.deb /tmp/

# Install the deb package, and print out contents of expected changed locations
RUN yum -y update && yum install -y\
    /tmp/rocprim-*.deb \
  && rm -f /tmp/*.deb \
  && yum -y clean all \
  && rm -rf /var/lib/apt/lists/* \
  && printf "ls -la /etc/ld.so.conf.d/\n" && ls -la /etc/ld.so.conf.d/ \
  && printf "ls -la /opt/rocm/include\n" && ls -la /opt/rocm/include \
  && printf "ls -la /opt/rocm/lib\n" && ls -la /opt/rocm/lib \
  && printf "ls -la /opt/rocm/lib/cmake\n" && ls -la /opt/rocm/lib/cmake
