name: github-AT2

on: 
  pull_request:
    paths-ignore:
    - '**/*.rst'
    - '**/*.md'
    - '**/requirements.txt'
    - '**/*.py'
    - 'docs/**'
    types: [ opened, reopened, synchronize ]

permissions:
  contents: none

# Cancels any in progress 'workflow' associated with this PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  KOKKOS_VERSION: 5.0.2

jobs:
  h100_lychee:
    uses: ./.github/workflows/h100_lychee.yml
    with:
      kokkos_version: 5.0.2
  v100_kumquat:
    uses: ./.github/workflows/v100_kumquat.yml
    with:
      kokkos_version: 5.0.2
      kokkos_previous_version: 4.7.02
  host:
    uses: ./.github/workflows/host.yml
    with:
      kokkos_version: 5.0.2
  mi210:
    uses: ./.github/workflows/mi210.yml
    with:
      kokkos_version: 5.0.2
