name: github-BDW

on:
  pull_request:
    paths-ignore:
    - '**/*.rst'
    - '**/*.md'
    - '**/requirements.txt'
    - '**/*.py'
    - 'docs/**'
    types: [ opened, reopened, synchronize ]
  pull_request_review:
    types:
      - submitted

permissions:
  contents: none

# Cancels any in progress 'workflow' associated with this PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
#  PR_BDW_GNU1020_OPENMP_LEFT_REL_NOETI:
#    name: PR_BDW_GNU1020_OPENMP_LEFT_REL_NOETI
#    runs-on: [kk-env-gcc-10.2.0-latest]
#    
#    steps:
#      - name: checkout_kokkos_kernels
#        uses: actions/checkout@v3
#        with:
#          path: kokkos-kernels
#
#      - name: checkout_kokkos
#        uses: actions/checkout@v3
#        with:
#          repository: kokkos/kokkos
#          ref: ${{ github.base_ref }}
#          path: kokkos
#
#      - name: configure_kokkos
#        run: |
#          mkdir -p kokkos/{build,install}
#          cd kokkos/build
#          cmake \
#            -DCMAKE_CXX_COMPILER=g++ \
#            -DCMAKE_CXX_FLAGS=-O3 \
#            -DCMAKE_EXE_LINKER_FLAGS= \
#            -DCMAKE_INSTALL_PREFIX=$PWD/../install \
#            -DKokkos_ENABLE_OPENMP=ON \
#            -DKokkos_ARCH_BDW=ON \
#            -DKokkos_ENABLE_TESTS=OFF \
#            -DKokkos_ENABLE_EXAMPLES=OFF \
#            -DCMAKE_VERBOSE_MAKEFILE=ON \
#            -DCMAKE_CXX_EXTENSIONS=OFF \
#            -DCMAKE_CXX_STANDARD=17 \
#            -DBUILD_SHARED_LIBS=OFF \
#            -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF \
#            -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF \
#            ..
#
#      - name: build_and_install_kokkos
#        working-directory: kokkos/build
#        run: make -j12 install
#
#      - name: configure_kokkos_kernels
#        run: |
#          mkdir -p kokkos-kernels/{build,install}
#          cd kokkos-kernels/build
#          cmake \
#            -DCMAKE_CXX_COMPILER=g++ \
#            -DKokkos_DIR=$PWD/../../kokkos/install/lib64/cmake/Kokkos \
#            -DCMAKE_CXX_FLAGS="-O3 " \
#            -DCMAKE_INSTALL_PREFIX= \
#            -DKokkosKernels_ENABLE_TESTS_AND_PERFSUITE=OFF \
#            -DKokkosKernels_ENABLE_TESTS=ON \
#            -DKokkosKernels_ENABLE_PERFTESTS=ON \
#            -DKokkosKernels_ENABLE_EXAMPLES:BOOL=ON \
#            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF \
#            -DKokkosKernels_INST_COMPLEX_DOUBLE=ON \
#            -DKokkosKernels_INST_DOUBLE=ON \
#            -DKokkosKernels_INST_ORDINAL_INT=ON \
#            -DKokkosKernels_INST_OFFSET_SIZE_T=ON \
#            -DKokkosKernels_INST_OFFSET_INT=ON \
#            -DKokkosKernels_INST_LAYOUTLEFT=ON \
#            -DKokkosKernels_ENABLE_TPL_ROCSPARSE=OFF \
#            -DKokkosKernels_ENABLE_TPL_ROCBLAS=OFF \
#            -DKokkosKernels_ENABLE_TPL_CUSOLVER=OFF \
#            -DKokkosKernels_ENABLE_TPL_CUSPARSE=OFF \
#            -DKokkosKernels_ENABLE_TPL_CUBLAS=OFF \
#            -DCMAKE_EXE_LINKER_FLAGS="" \
#            -DBUILD_SHARED_LIBS=OFF \
#            -DKokkosKernels_TEST_ETI_ONLY=OFF \
#            -DKokkosKernels_ENABLE_DOCS=OFF \
#            ..
#
#      - name: build_kokkos_kernels
#        working-directory: kokkos-kernels/build
#        run: make -j12 all
#
#      - name: test
#        working-directory: kokkos-kernels/build
#        run: ctest --output-on-failure -V --timeout 3600
#
#  PR_BDW_GNU1020_THREADS_SERIAL_RIGHT_REL:
#    name: PR_BDW_GNU1020_THREADS_SERIAL_RIGHT_REL
#    runs-on: [kk-env-gcc-10.2.0-latest]
#
#    steps:
#      - name: checkout_kokkos_kernels
#        uses: actions/checkout@v3
#        with:
#          path: kokkos-kernels
#
#      - name: checkout_kokkos
#        uses: actions/checkout@v3
#        with:
#          repository: kokkos/kokkos
#          ref: ${{ github.base_ref }}
#          path: kokkos
#
#      - name: configure_kokkos
#        run: |
#          mkdir -p kokkos/{build,install}
#          cd kokkos/build
#          cmake \
#            -DCMAKE_CXX_COMPILER=g++ \
#            -DCMAKE_CXX_FLAGS=-O3  \
#            -DCMAKE_EXE_LINKER_FLAGS= \
#            -DCMAKE_INSTALL_PREFIX=$PWD/../install \
#            -DKokkos_ENABLE_SERIAL=ON \
#            -DKokkos_ENABLE_THREADS=ON \
#            -DKokkos_ARCH_BDW=ON \
#            -DKokkos_ENABLE_TESTS=OFF \
#            -DKokkos_ENABLE_EXAMPLES=OFF \
#            -DCMAKE_VERBOSE_MAKEFILE=ON \
#            -DCMAKE_CXX_EXTENSIONS=OFF \
#            -DCMAKE_CXX_STANDARD=17 \
#            -DBUILD_SHARED_LIBS=OFF \
#            -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF \
#            -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF \
#            -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF \
#            ..
#
#      - name: build_and_install_kokkos
#        working-directory: kokkos/build
#        run: make -j12 install
#
#      - name: configure_kokkos_kernels
#        run: |
#          mkdir -p kokkos-kernels/{build,install}
#          cd kokkos-kernels/build
#          cmake \
#            -DCMAKE_CXX_COMPILER=g++ \
#            -DKokkos_DIR=$PWD/../../kokkos/install/lib64/cmake/Kokkos \
#            -DCMAKE_CXX_FLAGS="-O3 " \
#            -DCMAKE_INSTALL_PREFIX= \
#            -DKokkosKernels_ENABLE_TESTS_AND_PERFSUITE=OFF \
#            -DKokkosKernels_ENABLE_TESTS=ON \
#            -DKokkosKernels_ENABLE_PERFTESTS=ON \
#            -DKokkosKernels_ENABLE_EXAMPLES:BOOL=ON \
#            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF \
#            -DKokkosKernels_INST_COMPLEX_DOUBLE=ON \
#            -DKokkosKernels_INST_DOUBLE=ON \
#            -DKokkosKernels_INST_ORDINAL_INT=ON \
#            -DKokkosKernels_INST_OFFSET_SIZE_T=ON \
#            -DKokkosKernels_INST_OFFSET_INT=ON \
#            -DKokkosKernels_INST_LAYOUTLEFT=ON \
#            -DKokkosKernels_ENABLE_TPL_ROCSPARSE=OFF \
#            -DKokkosKernels_ENABLE_TPL_ROCBLAS=OFF \
#            -DKokkosKernels_ENABLE_TPL_CUSOLVER=OFF \
#            -DKokkosKernels_ENABLE_TPL_CUSPARSE=OFF \
#            -DKokkosKernels_ENABLE_TPL_CUBLAS=OFF \
#            -DCMAKE_EXE_LINKER_FLAGS="" \
#            -DBUILD_SHARED_LIBS=OFF \
#            -DKokkosKernels_ENABLE_DOCS=OFF \
#            ..
#
#      - name: build_kokkos_kernels
#        working-directory: kokkos-kernels/build
#        run: make -j12 all
#
#      - name: test
#        working-directory: kokkos-kernels/build
#        run: ctest --output-on-failure -V --timeout 3600

  PR_BDW_GNU1020_OPENMP_SERIAL_LEFT_OPENBLAS_REL:
    name: PR_BDW_GNU1020_OPENMP_SERIAL_LEFT_OPENBLAS_REL
    runs-on: [kk-env-openblas-0.3.21-gcc-10.2.0-latest]
    
    steps:
      - name: checkout_kokkos_kernels
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          path: kokkos-kernels

      - name: checkout_kokkos
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: kokkos/kokkos
          ref: ${{ github.base_ref }}
          path: kokkos

      - name: configure_kokkos
        run: |
          mkdir -p kokkos/{build,install}
          cd kokkos/build

          cmake \
            -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_CXX_FLAGS=-O3 \
            -DCMAKE_EXE_LINKER_FLAGS= \
            -DCMAKE_INSTALL_PREFIX=$PWD/../install \
            -DKokkos_ENABLE_SERIAL=ON \
            -DKokkos_ENABLE_OPENMP=ON \
            -DKokkos_ARCH_BDW=ON \
            -DKokkos_ENABLE_TESTS=OFF \
            -DKokkos_ENABLE_EXAMPLES=OFF \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DCMAKE_CXX_EXTENSIONS=OFF \
            -DCMAKE_CXX_STANDARD=17 \
            -DBUILD_SHARED_LIBS=OFF \
            -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF \
            -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF \
            -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF \
            ..

      - name: build_and_install_kokkos
        working-directory: kokkos/build
        run: make -j12 install

      - name: configure_kokkos_kernels
        run: |
          mkdir -p kokkos-kernels/{build,install}
          cd kokkos-kernels/build

          cmake \
            -DCMAKE_CXX_COMPILER=g++ \
            -DKokkos_DIR=$PWD/../../kokkos/install/lib64/cmake/Kokkos \
            -DCMAKE_CXX_FLAGS="-O3 " \
            -DCMAKE_INSTALL_PREFIX= \
            -DKokkosKernels_ENABLE_TESTS_AND_PERFSUITE=OFF \
            -DKokkosKernels_ENABLE_TESTS=ON \
            -DKokkosKernels_ENABLE_PERFTESTS=ON \
            -DKokkosKernels_ENABLE_EXAMPLES:BOOL=ON \
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF \
            -DKokkosKernels_INST_COMPLEX_DOUBLE=ON \
            -DKokkosKernels_INST_DOUBLE=ON \
            -DKokkosKernels_INST_ORDINAL_INT=ON \
            -DKokkosKernels_INST_OFFSET_SIZE_T=ON \
            -DKokkosKernels_INST_OFFSET_INT=ON \
            -DKokkosKernels_INST_LAYOUTLEFT=ON \
            -DKokkosKernels_ENABLE_TPL_ROCSPARSE=OFF \
            -DKokkosKernels_ENABLE_TPL_ROCBLAS=OFF \
            -DKokkosKernels_ENABLE_TPL_CUSOLVER=OFF \
            -DKokkosKernels_ENABLE_TPL_CUSPARSE=OFF \
            -DKokkosKernels_ENABLE_TPL_CUBLAS=OFF \
            -DKokkosKernels_ENABLE_TPL_BLAS=ON \
            -DCMAKE_EXE_LINKER_FLAGS="" \
            -DBUILD_SHARED_LIBS=OFF \
            -DKokkosKernels_ENABLE_DOCS=OFF \
            ..

      - name: build_kokkos_kernels
        working-directory: kokkos-kernels/build
        run: make -j12 all

      - name: test
        working-directory: kokkos-kernels/build
        run: ctest --output-on-failure -V --timeout 3600

#  PR_BDW_CLANG1001_THREADS_SERIAL_LEFT_REL:
#    name: PR_BDW_CLANG1001_THREADS_SERIAL_LEFT_REL
#    runs-on: [kk-env-llvm-10.0.1-latest]
#
#    steps:
#      - name: checkout_kokkos_kernels
#        uses: actions/checkout@v3
#        with:
#          path: kokkos-kernels
#
#      - name: checkout_kokkos
#        uses: actions/checkout@v3
#        with:
#          repository: kokkos/kokkos
#          ref: ${{ github.base_ref }}
#          path: kokkos
#
#      - name: configure_kokkos
#        run: |
#          mkdir -p kokkos/{build,install}
#          cd kokkos/build
#          cmake \
#            -DCMAKE_CXX_COMPILER=clang++ \
#            -DCMAKE_CXX_FLAGS="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized" \
#            -DCMAKE_EXE_LINKER_FLAGS= \
#            -DCMAKE_INSTALL_PREFIX=$PWD/../install \
#            -DKokkos_ENABLE_SERIAL=ON \
#            -DKokkos_ENABLE_THREADS=ON \
#            -DKokkos_ARCH_BDW=ON \
#            -DKokkos_ENABLE_TESTS=OFF \
#            -DKokkos_ENABLE_EXAMPLES=OFF \
#            -DCMAKE_VERBOSE_MAKEFILE=ON \
#            -DCMAKE_CXX_EXTENSIONS=OFF \
#            -DCMAKE_CXX_STANDARD=17 \
#            -DBUILD_SHARED_LIBS=OFF \
#            -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF \
#            -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF \
#            -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF \
#            ..
#
#      - name: build_and_install_kokkos
#        working-directory: kokkos/build
#        run: make -j12 install
#
#      - name: configure_kokkos_kernels
#        run: |
#          mkdir -p kokkos-kernels/{build,install}
#          cd kokkos-kernels/build
#          cmake \
#            -DCMAKE_CXX_COMPILER=clang++ \
#            -DKokkos_DIR=$PWD/../../kokkos/install/lib64/cmake/Kokkos \
#            -DCMAKE_CXX_FLAGS="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized" \
#            -DCMAKE_INSTALL_PREFIX= \
#            -DKokkosKernels_ENABLE_TESTS_AND_PERFSUITE=OFF \
#            -DKokkosKernels_ENABLE_TESTS=ON \
#            -DKokkosKernels_ENABLE_PERFTESTS=ON \
#            -DKokkosKernels_ENABLE_EXAMPLES:BOOL=ON \
#            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF \
#            -DKokkosKernels_INST_COMPLEX_DOUBLE=ON \
#            -DKokkosKernels_INST_DOUBLE=ON \
#            -DKokkosKernels_INST_ORDINAL_INT=ON \
#            -DKokkosKernels_INST_OFFSET_SIZE_T=ON \
#            -DKokkosKernels_INST_OFFSET_INT=ON \
#            -DKokkosKernels_INST_LAYOUTLEFT=ON \
#            -DKokkosKernels_ENABLE_TPL_ROCSPARSE=OFF \
#            -DKokkosKernels_ENABLE_TPL_ROCBLAS=OFF \
#            -DKokkosKernels_ENABLE_TPL_CUSOLVER=OFF \
#            -DKokkosKernels_ENABLE_TPL_CUSPARSE=OFF \
#            -DKokkosKernels_ENABLE_TPL_CUBLAS=OFF \
#            -DCMAKE_EXE_LINKER_FLAGS="" \
#            -DBUILD_SHARED_LIBS=OFF \
#            -DKokkosKernels_ENABLE_DOCS=OFF \
#            ..
#
#      - name: build_kokkos_kernels
#        working-directory: kokkos-kernels/build
#        run: make -j12 all
#
#      - name: test
#        working-directory: kokkos-kernels/build
#        run: ctest --output-on-failure -V --timeout 3600
#
#    