name: Reusable SPR workflow

permissions:
  contents: none

on:
  workflow_call:
    inputs:
      kokkos_version:
        description: 'The Kokkos Core version to build'
        default: ''
        required: true
        type: string

jobs:
  PR_SPR_ONEAPI202310_OPENMP_LEFT_MKLBLAS_MKLLAPACK_REL:
    name: PR_SPR_ONEAPI202310_OPENMP_LEFT_MKLBLAS_MKLLAPACK_REL
    runs-on: [kk-env-intel-oneapi-compilers-2023.1.0-latest]
    
    steps:
      - name: checkout_kokkos_kernels
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          path: kokkos-kernels

      - name: checkout_kokkos
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          repository: kokkos/kokkos
          ref: ${{ inputs.kokkos_version }}
          path: kokkos

      - name: configure
        run: |
          mkdir -p build
          cd build
          ../kokkos-kernels/cm_generate_makefile.bash \
            --with-openmp \
            --with-serial \
            --arch=SPR \
            --compiler=icpx \
            --cxxflags="-fp-model=precise" \
            --with-scalars=double,complex_double,float,complex_float \
            --with-ordinals=int,int64_t \
            --with-offsets=int,size_t \
            --with-tpls=mkl \
            --kokkos-cmake-flags=-DKokkos_ENABLE_ONEDPL=OFF \
            --kokkos-path=$PWD/../kokkos

      - name: build
        working-directory: build
        run: make -j8

      - name: test
        working-directory: build
        run: ctest --output-on-failure -V --timeout 3600