name: Reusable VOLTA70 workflow

permissions:
  contents: none

on:
  workflow_call:
    inputs:
      kokkos_version:
        description: 'The Kokkos Core version to build'
        default: ''
        required: true
        type: string

jobs:
  PR_VOLTA70_CUDA1122_CUDA_LEFT_RIGHT_REL:
    name: PR_VOLTA70_CUDA1122_CUDA_LEFT_RIGHT_REL
    runs-on: [kk-env-cuda-11.2.2-gcc-8.4.0-latest]
    
    steps:
      - name: checkout_kokkos_kernels
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: kokkos-kernels

      - name: checkout_kokkos
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: kokkos/kokkos
          ref: ${{ inputs.kokkos_version }}
          path: kokkos

      - name: configure_kokkos
        run: |
          mkdir -p kokkos/{build,install}
          cd kokkos/build
          cmake -DCMAKE_CXX_COMPILER=$PWD/../bin/nvcc_wrapper \
            -DCMAKE_INSTALL_PREFIX=$PWD/../install \
            -DKokkos_ENABLE_CUDA=ON \
            -DKokkos_ARCH_VOLTA70=ON \
            -DKokkos_ENABLE_TESTS=OFF \
            -DKokkos_ENABLE_EXAMPLES=OFF \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DCMAKE_CXX_EXTENSIONS=OFF \
            -DBUILD_SHARED_LIBS=OFF \
            -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF \
            -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF \
            ..

      - name: build_and_install_kokkos
        working-directory: kokkos/build
        run: make -j12 install

      - name: configure_kokkos_kernels
        run: |
          mkdir -p kokkos-kernels/{build,install}
          cd kokkos-kernels/build
          cmake \
            -DCMAKE_CXX_COMPILER=$PWD/../../kokkos/bin/nvcc_wrapper \
            -DKokkos_ROOT="$PWD/../../kokkos/install" \
            -DKokkosKernels_ENABLE_TESTS_AND_PERFSUITE=OFF \
            -DKokkosKernels_ENABLE_TESTS=ON \
            -DKokkosKernels_ENABLE_PERFTESTS=ON \
            -DKokkosKernels_ENABLE_EXAMPLES:BOOL=ON \
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF \
            -DKokkosKernels_ENABLE_TPL_CUSOLVER=OFF \
            -DKokkosKernels_ENABLE_TPL_CUSPARSE=OFF \
            -DKokkosKernels_ENABLE_TPL_CUBLAS=OFF \
            -DKokkosKernels_INST_LAYOUTRIGHT=ON \
            -DBUILD_SHARED_LIBS=OFF \
            -DKokkosKernels_ENABLE_DOCS=OFF \
            ..

      - name: build_kokkos_kernels
        working-directory: kokkos-kernels/build
        run: make -j12 all

      - name: test
        working-directory: kokkos-kernels/build
        run: ctest --output-on-failure --timeout 3600

  PR_VOLTA70_GCC930_CLANG13_CUDA10_CUDA_LEFT_OPENBLAS_REL:
    name: PR_VOLTA70_GCC930_CLANG13_CUDA10_CUDA_LEFT_OPENBLAS_REL
    runs-on: [kk-env-cuda-10.1.243-openblas-0.3.20-llvm-13.0.0-latest]
    
    steps:
      - name: checkout_kokkos_kernels
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: kokkos-kernels

      - name: checkout_kokkos
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: kokkos/kokkos
          ref: ${{ inputs.kokkos_version }}
          path: kokkos

      - name: configure_kokkos
        run: |
          mkdir -p kokkos/{build,install}
          cd kokkos/build
          NVCC=$(which clang++)
          cmake -DCMAKE_CXX_COMPILER=$NVCC \
            -DCMAKE_CXX_FLAGS="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized" \
            -DCMAKE_INSTALL_PREFIX=$PWD/../install \
            -DKokkos_ENABLE_CUDA=ON \
            -DKokkos_ARCH_VOLTA70=ON \
            -DKokkos_ENABLE_TESTS=OFF \
            -DKokkos_ENABLE_EXAMPLES=OFF \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DCMAKE_CXX_EXTENSIONS=OFF \
            -DCMAKE_CXX_STANDARD=17 \
            -DBUILD_SHARED_LIBS=OFF \
            -DKokkos_ENABLE_DEPRECATED_CODE_4=OFF \
            ..

      - name: build_and_install_kokkos
        working-directory: kokkos/build
        run: make -j12 install

      - name: configure_kokkos_kernels
        run: |
          mkdir -p kokkos-kernels/{build,install}
          cd kokkos-kernels/build
          NVCC=$(which clang++)
          cmake \
            -DCMAKE_CXX_COMPILER=$NVCC \
            -DKokkos_ROOT="$PWD/../../kokkos/install" \
            -DCMAKE_CXX_FLAGS="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized" \
            -DKokkosKernels_ENABLE_TESTS_AND_PERFSUITE=OFF \
            -DKokkosKernels_ENABLE_TESTS=ON \
            -DKokkosKernels_ENABLE_PERFTESTS=ON \
            -DKokkosKernels_ENABLE_EXAMPLES:BOOL=ON \
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF \
            -DKokkosKernels_INST_COMPLEX_DOUBLE=ON \
            -DKokkosKernels_INST_DOUBLE=ON \
            -DKokkosKernels_INST_ORDINAL_INT=ON \
            -DKokkosKernels_INST_OFFSET_SIZE_T=ON \
            -DKokkosKernels_INST_OFFSET_INT=ON \
            -DKokkosKernels_INST_LAYOUTLEFT=ON \
            -DKokkosKernels_ENABLE_TPL_CUSOLVER=OFF \
            -DKokkosKernels_ENABLE_TPL_BLAS=ON \
            -DKokkosKernels_ENABLE_TPL_CUBLAS=ON \
            -DKokkosKernels_ENABLE_TPL_CUSPARSE=ON \
            -DCMAKE_EXE_LINKER_FLAGS="-lgfortran -lm" \
            -DBUILD_SHARED_LIBS=OFF \
            -DKokkosKernels_ENABLE_DOCS=OFF \
            ..

      - name: build_kokkos_kernels
        working-directory: kokkos-kernels/build
        run: make -j12 all

      - name: test EXCLUDE serial\."asum|nrm1"_complex_double
        working-directory: kokkos-kernels/build
        run: ctest --output-on-failure --timeout 3600 -E ".*(asum|nrm1).*"